name: Daily Job Scraping

on:
  schedule:
    - cron: '0 0 * * *'  # Spuštění každý den o půlnoci
  workflow_dispatch:      # Možnost manuálního spuštění

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create credentials file
      run: |
        cat > credentials.json << 'EOL'
        ${{ secrets.GOOGLE_CREDENTIALS }}
        EOL
      
    - name: Debug credentials file
      run: |
        cat credentials.json | grep -v "private_key" | head -n 5
      
    - name: Run scraper
      env:
        DOCUMENT_ID: ${{ secrets.DOCUMENT_ID }}
      run: python Scraper/jobs_scraper.py
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-logs
        path: scraper.log
        retention-days: 7

    - name: Clean up credentials
      if: always()
      run: rm -f credentials.json 